name: Release

on:
  push:
    branches:
      - main

jobs:
  release-action:
    runs-on: ubuntu-latest
    name: Release action
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup node.js
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 12

      - name: Install dependencies
        run: npm ci

      - name: Tests
        run: npm run test

      - uses: TheRealWaldo/quick-release@v0.3.0
        with:
          token: ${{ secrets.AUTO_PAT }}
          replace-files: README.md,package.json
          git-user-email: 68967746+TRW-bot@users.noreply.github.com
          assignees: TheRealWaldo
          publish-npm: true
