name: Release

on:
  push:
    branches:
      - main

jobs:
  release-action:
    runs-on: ubuntu-latest
    name: Release action
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup node.js
        uses: actions/setup-node@v4.0.0
        with:
          node-version: 12
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Tests
        run: npm run test

      - name: Release
        id: release
        uses: TheRealWaldo/quick-release@v0.4.1
        with:
          token: ${{ secrets.AUTO_PAT }}
          replace-files: README.md,package.json
          git-user-email: 68967746+TRW-bot@users.noreply.github.com
          assignees: TheRealWaldo

      - name: Publish
        run: npm publish
        if: steps.release.outputs.status == 'release'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
